version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - PORT=3000
      - RABBITMQ_URL=amqp://rabbitmq
    networks:
      - app-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
    environment:
      - PORT=3001
      - JWT_SECRET=olesya251925
      - MONGO_URI=mongodb://mongo:27017/backend-5lab
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - app-network

  course-service:
    build:
      context: ./course-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./course-service/src/uploads:/app/src/uploads
      - ./course-service/src/images:/app/src/images
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
    environment:
      - PORT=3002
      - JWT_SECRET=olesya251925
      - MONGO_URI=mongodb://mongo:27017/backend-5lab
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - app-network

  tag-service:
    build:
      context: ./tag-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
    environment:
      - PORT=3003
      - JWT_SECRET=olesya251925
      - MONGO_URI=mongodb://mongo:27017/backend-5lab
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - app-network

  lesson-service:
    build:
      context: ./lesson-service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
    environment:
      - PORT=3004
      - JWT_SECRET=olesya251925
      - MONGO_URI=mongodb://mongo:27017/backend-5lab
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - app-network

  comment-service:
    build:
      context: ./comment-service
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
    environment:
      - PORT=3005
      - JWT_SECRET=olesya251925
      - MONGO_URI=mongodb://mongo:27017/backend-5lab
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - app-network

  enrollment-service:
    build:
      context: ./enrollment-service
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
    environment:
      - PORT=3006
      - JWT_SECRET=olesya251925
      - MONGO_URI=mongodb://mongo:27017/backend-5lab
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - app-network

  status-service:
    build:
      context: ./status-service
      dockerfile: Dockerfile
    ports:
      - "3007:3007"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - PORT=3007
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
