version: "3.8"

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    environment:
      - PORT=3000
      - RABBITMQ_URL=amqp://rabbitmq
    networks:
      - app-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
      - mongo
    environment:
      - PORT=3001
      - JWT_SECRET=your_jwt_secret
      - MONGO_URI=mongodb://mongo:27017/backend-5lab
    networks:
      - app-network

  status-service:
    build:
      context: ./status-service
      dockerfile: Dockerfile
    ports:
      - "3007:3007"
    depends_on:
      - rabbitmq
    environment:
      - PORT=3007
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
