services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  api-gateway:
    build: ./services/gateway
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - user-service
      - course-service
      - tag-service
      - lesson-service
      - comment-service
      - enrollment-service
    networks:
      - app-network

  user-service:
    build: ./services/user-service
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
      - status-service
    networks:
      - app-network

  course-service:
    build: ./services/course-service
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
      - status-service
      - tag-service
    networks:
      - app-network

  tag-service:
    build: ./services/tag-service
    ports:
      - "3003:3003"
    depends_on:
      - rabbitmq
      - status-service
    networks:
      - app-network

  lesson-service:
    build: ./services/lesson-service
    ports:
      - "3004:3004"
    depends_on:
      - rabbitmq
      - status-service
    networks:
      - app-network

  comment-service:
    build: ./services/comment-service
    ports:
      - "3005:3005"
    depends_on:
      - rabbitmq
      - status-service
    networks:
      - app-network

  enrollment-service:
    build: ./services/enrollment-service
    ports:
      - "3006:3006"
    depends_on:
      - rabbitmq
      - status-service
    networks:
      - app-network

  status-service:
    build: ./services/status-service
    ports:
      - "3007:3007"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
