FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./

RUN yarn install --frozen-lockfile

COPY src ./src

RUN mkdir -p /app/user-service/src/models

CMD ["yarn", "run", "start"]